executable = /home/nsaini/miniconda3/envs/mcms/bin/python
arguments = /is/ps3/nsaini/projects/mcms/src/mcms/fitting_scripts/fitting_in_vp_latent_multires.py volley_data 0
error = /is/cluster/nsaini/cluster_logs/error.volley_data_$(Process).err
output = /is/cluster/nsaini/cluster_logs/output.volley_data_$(Process).out
log = /is/cluster/nsaini/cluster_logs/log.volley_data_$(Process).log
request_memory = 100000
request_cpus = 30
request_gpus = 1
getenv = True
concurrency_limits=user.mytag:1
requirements = TARGET.CUDACapability>=6.0
on_exit_hold = (ExitCode =?= 3)
on_exit_hold_reason = "Checkpointed, will resume"
on_exit_hold_subcode = 2
periodic_release = ( (JobStatus =?= 5) && (HoldReasonCode =?= 3) && (HoldReasonSubCode =?= 2) )
queue 1